Feature/login form
Vladacdc/BookLandClient pull request #4
Opened 2020-12-08 22:13 UTC by UkhachevychT

2020-12-08 22:44 UTC, Vladacdc requested changes
Mostly minor changes except for bootstrap.

2020-12-08 22:44 UTC, Vladacdc commented on ClientApp/src/index.html
> +  <link href="//netdna.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" />
Add bootstrap as a package, please. And why not to use v5.

2020-12-08 22:44 UTC, Vladacdc commented on ClientApp/src/app/account/components/register/register.component.ts
> +//   selector: 'app-register',
Remove commented line

2020-12-08 22:44 UTC, Vladacdc commented on ClientApp/src/app/app-routing.module.ts
> +  //   redirectTo: 'books'
Remove commented lines

2020-12-08 22:44 UTC, Vladacdc commented on ClientApp/src/app/users/components/layout/layout.component.ts
> +  // selector: 'app-layout',
Remove commented line

2020-12-13 15:31 UTC, UkhachevychT commented on ClientApp/src/index.html
> +  <link href="//netdna.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" />
v5 is in beta, let's stick to 4.5.3

2020-12-13 15:41 UTC, Vladacdc approved these changes

2020-12-14 20:35 UTC, merged